import { useState } from "react";
import axios from "axios";
import ReactMarkdown from "react-markdown";

const API = "http://localhost:8000";

export default function PredictPanel() {
  const [analysis, setAnalysis] = useState(null);
  const [loading, setLoading]   = useState(false);
  const [error, setError]       = useState(null);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await axios.get(`${API}/ai-analysis`);
      if (res.data.status === "success") {
        setAnalysis(res.data.analysis);
      } else {
        setError(res.data.error || "Failed to generate AI analysis.");
      }
    } catch (e) {
      setError("AI Generation failed. Is the backend running?");
    }
    setLoading(false);
  };

  return (
    <div className="glass-card" style={{ padding: "20px", display: "flex", flexDirection: "column" }}>
      <div className="section-title" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span>✨ Gemini AI Executive Summary</span>
        {analysis && (
          <span style={{ fontSize: "11px", color: "var(--cyan)", fontWeight: 400, background: "rgba(0,212,255,0.1)", padding: "2px 8px", borderRadius: "10px" }}>
            Generated by gemini-3-flash-preview
          </span>
        )}
      </div>
      
      {!analysis && !loading && (
        <div style={{ flex: 1, display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", textAlign: "center", padding: "20px" }}>
          <div style={{ fontSize: "32px", marginBottom: "12px" }}>🤖</div>
          <h3 style={{ color: "var(--text-primary)", fontSize: "14px", marginBottom: "6px" }}>Government Policy Report</h3>
          <p style={{ color: "var(--text-muted)", fontSize: "12px", marginBottom: "20px", maxWidth: "250px" }}>
            Synthesize real-time satellite data, pollution trends, and festival impacts into an actionable intelligence brief.
          </p>
          <button
            className="btn-primary"
            onClick={handleGenerate}
            style={{ padding: "10px 20px", fontSize: "13px", display: "flex", alignItems: "center", gap: "8px" }}
          >
            <span>✨ Generate Briefing</span>
          </button>
        </div>
      )}

      {loading && (
        <div style={{ flex: 1, display: "flex", flexDirection: "column", justifyContent: "center", alignItems: "center", padding: "40px 20px" }}>
          <div className="loading-orbit" style={{ width: "40px", height: "40px", marginBottom: "16px" }} />
          <div style={{ color: "var(--cyan)", fontSize: "13px", fontWeight: 600 }}>Gemini is analyzing...</div>
          <div style={{ color: "var(--text-muted)", fontSize: "11px", marginTop: "4px" }}>Cross-referencing orbital data with cultural events</div>
        </div>
      )}

      {error && (
        <div style={{ color: "var(--red)", fontSize: "12px", marginTop: "20px", textAlign: "center", padding: "20px", background: "rgba(255,59,59,0.1)", borderRadius: "8px" }}>
          ⚠️ {error}
        </div>
      )}

      {analysis && !loading && (
        <div className="fade-in" style={{ 
          marginTop: "16px", 
          fontSize: "13px", 
          lineHeight: "1.6", 
          color: "var(--text-primary)",
          background: "rgba(0,0,0,0.2)",
          padding: "16px 20px",
          borderRadius: "8px",
          borderLeft: "3px solid var(--cyan)",
          flex: 1,
          overflowY: "auto",
          maxHeight: "300px"
        }}>
          <ReactMarkdown
            components={{
              h1: ({node, ...props}) => <h1 style={{fontSize: "16px", color: "var(--cyan)", marginBottom: "8px", marginTop: "12px"}} {...props} />,
              h2: ({node, ...props}) => <h2 style={{fontSize: "15px", color: "#fff", marginBottom: "8px", marginTop: "12px"}} {...props} />,
              h3: ({node, ...props}) => <h3 style={{fontSize: "14px", color: "#fff", marginBottom: "8px", marginTop: "12px"}} {...props} />,
              ul: ({node, ...props}) => <ul style={{paddingLeft: "20px", marginBottom: "12px"}} {...props} />,
              li: ({node, ...props}) => <li style={{marginBottom: "6px"}} {...props} />,
              strong: ({node, ...props}) => <strong style={{color: "var(--cyan)"}} {...props} />,
              p: ({node, ...props}) => <p style={{marginBottom: "12px"}} {...props} />
            }}
          >
            {analysis}
          </ReactMarkdown>
        </div>
      )}
      
      {analysis && !loading && (
        <div style={{ display: "flex", justifyContent: "flex-end", marginTop: "12px" }}>
            <button 
                onClick={handleGenerate} 
                style={{ 
                    background: "transparent", border: "1px solid var(--border)", 
                    color: "var(--text-muted)", padding: "4px 12px", borderRadius: "4px",
                    fontSize: "11px", cursor: "pointer", transition: "all 0.2s" 
                }}
                onMouseOver={(e) => e.target.style.background = 'rgba(255,255,255,0.05)'}
                onMouseOut={(e) => e.target.style.background = 'transparent'}
            >
                ↻ Regenerate
            </button>
        </div>
      )}
    </div>
  );
}
